# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = ["new_all_access_1-7cinzfkabuoaekpr25a53w@fastlyautomationaccount.com"]
cloned_from = "https://github.com/fastly/compute-starter-kit-javascript-default"
description = ""
language = "javascript"
manifest_version = 3
name = "paywall-backend"
service_id = "zIOpM76iti000FPcTtRLYY"

[local_server]

[scripts]
  build = "npm run build"
  post_init = "npm install"
